site_name: COMP423 Course Notes
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate  # Corrected spelling here
    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - 'stylesheets.css'

extra:
  annotate:
    json: [.s2]  # Enable annotation within JSON files


